module.exports = class Data1664991715036 {
  name = 'Data1664991715036'

  async up(db) {
    await db.query(`DROP INDEX "public"."IDX_c7db3993fbe2ec59bbc9f450df"`)
    await db.query(`DROP INDEX "public"."IDX_142f352835c698a35eacbeb2f5"`)
    await db.query(`DROP INDEX "public"."IDX_579e39f71ef5f3b2a6839cd70b"`)
    await db.query(`DROP INDEX "public"."IDX_6e232918078798b1fade21dcf8"`)
    await db.query(`DROP INDEX "public"."IDX_8b212022b7428232091e2f8aa5"`)
    await db.query(`DROP INDEX "public"."IDX_79f0db0ed220b1dcb271c24c47"`)
    await db.query(`DROP INDEX "public"."IDX_8d62e222f606c249fb4046ad63"`)
    await db.query(`DROP INDEX "public"."IDX_cf47f5c1fa9b01b00dbfe2859a"`)
    await db.query(`DROP INDEX "public"."IDX_a032945f45cacda2d30f4286df"`)
    await db.query(`DROP INDEX "public"."IDX_b535fbe8ec6d832dde22065ebd"`)
    await db.query(`DROP INDEX "public"."IDX_1d7485faa58bd1844230e18c44"`)
    await db.query(`DROP INDEX "public"."IDX_a8a7fbbbb0d8305cd81eda6ac8"`)
    await db.query(`DROP INDEX "public"."IDX_7c2ed5bbb12e8b80905edfc8e2"`)
    await db.query(`DROP INDEX "public"."IDX_2c15918ff289396205521c5f3c"`)
    await db.query(`CREATE TABLE "block" ("id" character varying NOT NULL, "block_number" integer NOT NULL, "block_hash" text NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "chain_id" text NOT NULL, "ss58_format" integer NOT NULL, CONSTRAINT "PK_d0925763efb591c2e2ffb267572" PRIMARY KEY ("id"))`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "data"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "ss58_format"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "block_number"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "block_hash"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "timestamp"`)
    await db.query(`ALTER TABLE "call" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "call" DROP COLUMN "ss58_format"`)
    await db.query(`ALTER TABLE "call" DROP COLUMN "block_number"`)
    await db.query(`ALTER TABLE "call" DROP COLUMN "block_hash"`)
    await db.query(`ALTER TABLE "call" DROP COLUMN "timestamp"`)
    await db.query(`ALTER TABLE "event" DROP COLUMN "data"`)
    await db.query(`ALTER TABLE "event" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "event" DROP COLUMN "ss58_format"`)
    await db.query(`ALTER TABLE "event" DROP COLUMN "block_number"`)
    await db.query(`ALTER TABLE "event" DROP COLUMN "block_hash"`)
    await db.query(`ALTER TABLE "event" DROP COLUMN "timestamp"`)
    await db.query(`ALTER TABLE "extrinsic" ADD "version" integer NOT NULL`)
    await db.query(`ALTER TABLE "extrinsic" ADD "hash" text NOT NULL`)
    await db.query(`ALTER TABLE "extrinsic" ADD "fee" numeric`)
    await db.query(`ALTER TABLE "extrinsic" ADD "tip" numeric`)
    await db.query(`ALTER TABLE "extrinsic" ADD "success" boolean`)
    await db.query(`ALTER TABLE "extrinsic" ADD "error" text`)
    await db.query(`ALTER TABLE "extrinsic" ADD "signer" text`)
    await db.query(`ALTER TABLE "extrinsic" ADD "signature" text`)
    await db.query(`ALTER TABLE "extrinsic" ADD "signature_type" text`)
    await db.query(`ALTER TABLE "extrinsic" ADD "block_id" character varying NOT NULL`)
    await db.query(`ALTER TABLE "call" ADD "block_id" character varying NOT NULL`)
    await db.query(`ALTER TABLE "event" ADD "args" jsonb`)
    await db.query(`ALTER TABLE "event" ADD "phase" text NOT NULL`)
    await db.query(`ALTER TABLE "event" ADD "index_in_block" integer NOT NULL`)
    await db.query(`ALTER TABLE "event" ADD "block_id" character varying NOT NULL`)
    await db.query(`ALTER TABLE "call" ALTER COLUMN "name" SET NOT NULL`)
    await db.query(`ALTER TABLE "event" ALTER COLUMN "name" SET NOT NULL`)
    await db.query(`CREATE INDEX "IDX_a3b99daba1259dab0dd040d4f7" ON "extrinsic" ("block_id") `)
    await db.query(`CREATE INDEX "IDX_bd3f11fd4110d60ac8b96cd62f" ON "call" ("block_id") `)
    await db.query(`CREATE INDEX "IDX_2b0d35d675c4f99751855c4502" ON "event" ("block_id") `)
    await db.query(`ALTER TABLE "extrinsic" ADD CONSTRAINT "FK_a3b99daba1259dab0dd040d4f74" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "call" ADD CONSTRAINT "FK_bd3f11fd4110d60ac8b96cd62f3" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_2b0d35d675c4f99751855c45021" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
  }

  async down(db) {
    await db.query(`CREATE INDEX "IDX_c7db3993fbe2ec59bbc9f450df" ON "extrinsic" ("chain_id") `)
    await db.query(`CREATE INDEX "IDX_142f352835c698a35eacbeb2f5" ON "extrinsic" ("block_number") `)
    await db.query(`CREATE INDEX "IDX_579e39f71ef5f3b2a6839cd70b" ON "extrinsic" ("block_hash") `)
    await db.query(`CREATE INDEX "IDX_6e232918078798b1fade21dcf8" ON "extrinsic" ("timestamp") `)
    await db.query(`CREATE INDEX "IDX_8b212022b7428232091e2f8aa5" ON "call" ("name") `)
    await db.query(`CREATE INDEX "IDX_79f0db0ed220b1dcb271c24c47" ON "call" ("chain_id") `)
    await db.query(`CREATE INDEX "IDX_8d62e222f606c249fb4046ad63" ON "call" ("block_number") `)
    await db.query(`CREATE INDEX "IDX_cf47f5c1fa9b01b00dbfe2859a" ON "call" ("block_hash") `)
    await db.query(`CREATE INDEX "IDX_a032945f45cacda2d30f4286df" ON "call" ("timestamp") `)
    await db.query(`CREATE INDEX "IDX_b535fbe8ec6d832dde22065ebd" ON "event" ("name") `)
    await db.query(`CREATE INDEX "IDX_1d7485faa58bd1844230e18c44" ON "event" ("chain_id") `)
    await db.query(`CREATE INDEX "IDX_a8a7fbbbb0d8305cd81eda6ac8" ON "event" ("block_number") `)
    await db.query(`CREATE INDEX "IDX_7c2ed5bbb12e8b80905edfc8e2" ON "event" ("block_hash") `)
    await db.query(`CREATE INDEX "IDX_2c15918ff289396205521c5f3c" ON "event" ("timestamp") `)
    await db.query(`DROP TABLE "block"`)
    await db.query(`ALTER TABLE "extrinsic" ADD "data" jsonb`)
    await db.query(`ALTER TABLE "extrinsic" ADD "chain_id" text NOT NULL`)
    await db.query(`ALTER TABLE "extrinsic" ADD "ss58_format" integer NOT NULL`)
    await db.query(`ALTER TABLE "extrinsic" ADD "block_number" integer NOT NULL`)
    await db.query(`ALTER TABLE "extrinsic" ADD "block_hash" text NOT NULL`)
    await db.query(`ALTER TABLE "extrinsic" ADD "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL`)
    await db.query(`ALTER TABLE "call" ADD "chain_id" text NOT NULL`)
    await db.query(`ALTER TABLE "call" ADD "ss58_format" integer NOT NULL`)
    await db.query(`ALTER TABLE "call" ADD "block_number" integer NOT NULL`)
    await db.query(`ALTER TABLE "call" ADD "block_hash" text NOT NULL`)
    await db.query(`ALTER TABLE "call" ADD "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL`)
    await db.query(`ALTER TABLE "event" ADD "data" jsonb`)
    await db.query(`ALTER TABLE "event" ADD "chain_id" text NOT NULL`)
    await db.query(`ALTER TABLE "event" ADD "ss58_format" integer NOT NULL`)
    await db.query(`ALTER TABLE "event" ADD "block_number" integer NOT NULL`)
    await db.query(`ALTER TABLE "event" ADD "block_hash" text NOT NULL`)
    await db.query(`ALTER TABLE "event" ADD "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "version"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "hash"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "fee"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "tip"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "success"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "error"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "signer"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "signature"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "signature_type"`)
    await db.query(`ALTER TABLE "extrinsic" DROP COLUMN "block_id"`)
    await db.query(`ALTER TABLE "call" DROP COLUMN "block_id"`)
    await db.query(`ALTER TABLE "event" DROP COLUMN "args"`)
    await db.query(`ALTER TABLE "event" DROP COLUMN "phase"`)
    await db.query(`ALTER TABLE "event" DROP COLUMN "index_in_block"`)
    await db.query(`ALTER TABLE "event" DROP COLUMN "block_id"`)
    await db.query(`ALTER TABLE "call" ALTER COLUMN "name" DROP NOT NULL`)
    await db.query(`ALTER TABLE "event" ALTER COLUMN "name" DROP NOT NULL`)
    await db.query(`DROP INDEX "public"."IDX_a3b99daba1259dab0dd040d4f7"`)
    await db.query(`DROP INDEX "public"."IDX_bd3f11fd4110d60ac8b96cd62f"`)
    await db.query(`DROP INDEX "public"."IDX_2b0d35d675c4f99751855c4502"`)
    await db.query(`ALTER TABLE "extrinsic" DROP CONSTRAINT "FK_a3b99daba1259dab0dd040d4f74"`)
    await db.query(`ALTER TABLE "call" DROP CONSTRAINT "FK_bd3f11fd4110d60ac8b96cd62f3"`)
    await db.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_2b0d35d675c4f99751855c45021"`)
  }
}
